### ISSUE TITLE
When starting up VS Code the status of tests are remembered

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#24] opened 2021-08-11 15:55 UTC
After tests has run and in this case passed, it is reported as passed in test explorer (marked green). When restarting Visual Studio Code the green indicator is still present, and expanding the test file in test explorer the green mark is also added to the code file (if made visible using "Go To Test"). This is even if there has been code changes to the test that is marked green.

Suggest making all test to have "not run" indicator when starting VS Code. Otherwise it could give the impression that the test works with new code changes, even though the test was never run with those new code changes.

**Comment by JustinGrote** [comment] 2021-08-11 16:16
This is by Test API design. The test history is remembered, the green checkmarks/red errors should be a darker green when you start up again indicating they haven't been run lately, they'll turn bright green when you run them again. There is a option in the dropdown "clear all results" that will remove all previous run status
![image](https://user-images.githubusercontent.com/15258962/129065525-2394ef33-dc09-42d3-8c05-3dc9f40cc8df.png)

If you're seeing "bright" icons when you should be seeing "dim" ones, that's a bug, otherwise this is a "by design" wontfix

**Comment by JustinGrote** [comment] 2021-08-11 16:18
Demo:
![Capture](https://user-images.githubusercontent.com/15258962/129065747-609a7aca-bba1-436c-ada2-cba93e1e07b4.gif)

**Closed** 2021-08-11 17:43 UTC
