### ISSUE TITLE
RuntimeException: '-HaveParameter' is not a valid Should operator.

### ISSUE THREAD

**Issue by dethmourne** [pester/vscode-adapter#160] opened 2023-07-10 17:26 UTC
I was testing this against some tests that we've previously had no issue with and got the title error, repeated below:

`RuntimeException: '-HaveParameter' is not a valid Should operator.`

This does not match the Pester v5 documentation - [https://pester.dev/docs/assertions/#haveparameter](https://pester.dev/docs/assertions/#haveparameter)

**Comment by JustinGrote** [comment] 2023-07-10 19:22
Does it work when running invoke-pester normally? Are you sure you have the latest pester version installed for either winps or pwsh?

**Comment by JustinGrote** [comment] 2023-08-01 02:10
I cannot reproduce so make sure you have the latest Pester module and vscode extension and let me know if it persists, closing as unreproducible for now, works fine for me.
![image](https://github.com/pester/vscode-adapter/assets/15258962/9aa0aec5-1f05-4eda-8eb9-e38c0e0ddb31)

**Closed** 2023-08-01 02:11 UTC
Labels: bug, question
