### ISSUE TITLE
When running an individual test it tries to run all test

### ISSUE THREAD

**Issue by johlju** [pester/vscode-adapter#21] opened 2021-08-11 14:24 UTC
When choosing "Run Test" from the individual test "list" (first play symbol):

![image](https://user-images.githubusercontent.com/7189721/129046542-4059f8e8-cb36-4fdf-8bed-c3a01997fd9e.png)

it tries to run all found tests 

![image](https://user-images.githubusercontent.com/7189721/129046836-55752acd-d316-4a4a-b10f-4bd820339a77.png)

If choosing the second "play button" called "Debug Test" the individual test run as expected.

> FYI, it stops and asks for `MainGitBranch` because it runs a test that is not part of the project, a test that requires parameters to run. See issue #20.

**Comment by JustinGrote** [comment] 2021-08-11 14:30
I couldn't reproduce, I'll need to check out your repo.

**Comment by johlju** [comment] 2021-08-11 14:30
This seems to only happen when the list is collapsed. If expanding the test file to see individual tests inside the test file "Run Test" runs the test.

**Comment by JustinGrote** [comment] 2021-08-11 14:30
> This seems to only happen when the list is collapsed. If expanding the test file to see individual tests inside the test file "Run Test" runs the test.

Oh in that case this is a dupe of https://github.com/pester/vscode-adapter/issues/14

**Closed by JustinGrote** 2021-08-11 14:30 UTC

**Comment by johlju** [comment] 2021-08-17 15:09
@JustinGrote this was not fixed by #14.

![RunAllTests](https://user-images.githubusercontent.com/7189721/129751733-ab7d9f4d-c68c-4a13-9245-ba58137faf78.gif)

**Comment by JustinGrote** [comment] 2021-08-17 15:15
I saw it pop up "maingitbranch" there, do your tests require parameters or prompts? Interactive tests are not supported at the moment, that would be a separate enhancement.

**Comment by johlju** [comment] 2021-08-17 15:18
No, the issue is that it runs all 228 files even when I start just one. 

The prompt is from a test that should not be shown in test explorer at all (will be fixed when issue #20 is resolved).

**Comment by JustinGrote** [comment] 2021-08-17 15:35
The logic looks correct, when you click run it's passing your specific test file and line 447 as the inclusion filter.

Can you take that second PesterInterface command that it runs and change the verbosity to diagnostic and psot the output?

**Comment by johlju** [comment] 2021-08-17 15:47
When running "Debug Test" it always work. The problem is only with "Run Test".
![DebugTestSingleFile](https://user-images.githubusercontent.com/7189721/129758230-c3c46233-1b0b-424d-89e3-4d03e9301961.gif)

**Comment by johlju** [comment] 2021-08-17 15:50
Not sure you have any use of the output?

**Comment by JustinGrote** [comment] 2021-08-17 15:51
Debug and Run have different verbosity level settings in vscode, try setting them the same. Also make sure your $PesterPreference isn't set. 
![image](https://user-images.githubusercontent.com/15258962/129758976-c140f29a-b20f-4670-9d86-a74e87ddf9d3.png)

**Comment by johlju** [comment] 2021-08-17 15:56
Ah didn't know that setting - learned something new. 🙂 The one "Output Verbosity" were set to "FromPreference". Changing it to `Diagnostic` made "Run test" work. Setting it to any value other than "FromPreference" makes "Run Test" work.

**Comment by johlju** [comment] 2021-08-17 15:58
It should default to "Normal" when it is set to "FromPreference". Seems it does not?

**Comment by JustinGrote** [comment] 2021-08-17 15:59
Like I said probably a bug, I'll look into it and open this as a new issue.

**Comment by johlju** [comment] 2021-08-17 16:01
At least we found the issue. Thanks for the guidance! 😃
